### ISSUE TITLE
座子找到了吗？

### ISSUE THREAD

**Issue by yylwhy** [dragonbbc/hp400g2_macap2ngff#3]
座子找到了吗？
板子打完了。。座子问了好几家淘宝店都没有

**Comment by dragonbbc** [comment]
没，买个最便宜的转接板拆吧

**Comment by dragonbbc** [comment]
某宝看到有卖的了，关键字“苹果无线网卡 座”，但是价格算上运费还是比最便宜的转接板要贵，所以手头有风枪还是直接买转接板拆好了
